version: 1.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  matrix:
  - TOKEN:
      secure: EFVcZzUo9GxQ+slLBFQc2zhFzlfA9gULAy0cXu5m6mQbyzRYLxnAw3F+Z0Qx0Jef
    SECRET:
      secure: Wz456M9HIV13gTGBd4Eh1F+EsMcmwKgqJhG44BFaXTdC0TyX3k02vAoqOSMo9Xd7
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Working\NuGet\*.nupkg
  name: Nuget Package
deploy:
- provider: NuGet
  api_key:
    secure: XrGGizR8i1WOI8fgSFleT1AxAy6rqxgDOfGAEfOgqWr7QSqi2xUYr22OMGh6vxUf
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false